name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with HTML report
        run: |
          pytest --html=report.html --self-contained-html --log-cli-level=INFO

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html
